In [23]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import load_model
import ast
pd.set_option("display.max_rows", 500, "display.max_columns", 500)

In [24]:
traits = ["Openness", "Agreeableness", "Persistence", "Cooperativeness", "Openness to Experience", "Adjustment", "Ambition", "Learning Approach"]

f = open("CorrelatedQs.txt", "r")
questions_dict = f.readline()
questions_dict = ast.literal_eval(questions_dict)

tp = pd.read_excel('temp.xlsx')
# tp = pd.read_csv('questions.csv')

In [25]:
trait = "Openness"

model_Openness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness = model_Openness.predict(x)

y_pred_Openness

array([[44.892868]], dtype=float32)

In [26]:
trait = "Cooperativeness"

model_Cooperativeness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Cooperativeness = model_Cooperativeness.predict(x)

y_pred_Cooperativeness

array([[51.041485]], dtype=float32)

In [27]:
trait = "Adjustment"

model_Adjustment = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Adjustment = model_Adjustment.predict(x)

y_pred_Adjustment

array([[51.927986]], dtype=float32)

In [28]:
trait = "Persistence"

model_Persistence = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Persistence = model_Persistence.predict(x)

y_pred_Persistence

array([[30.730444]], dtype=float32)

In [29]:
trait = "Agreeableness"

model_Agreeableness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Agreeableness = model_Agreeableness.predict(x)

y_pred_Agreeableness

array([[69.3545]], dtype=float32)

In [30]:
trait = "Ambition"

model_Ambition = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Ambition = model_Ambition.predict(x)

y_pred_Ambition

array([[23.950094]], dtype=float32)

In [31]:
trait = "Openness to Experience"

model_Openness_to_Experience = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness_to_Experience = model_Openness_to_Experience.predict(x)

y_pred_Openness_to_Experience

array([[39.372784]], dtype=float32)

In [32]:
trait = "Learning Approach"

model_Learning_Approach = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Learning_Approach = model_Learning_Approach.predict(x)

y_pred_Learning_Approach

array([[7.0968194]], dtype=float32)